### ISSUE TITLE
Server side normal messages

### ISSUE THREAD

**Issue by sadiqhabib** [meanie/express-seed#1]
Hi I am using this project. And i really like it. I am little bit confused that you are not sending any normal server side message except status. So my my question is what is the best way to send normal messages like
`Account created check your email`  or `Password rest token sent to your email`
Thank you

**Comment by adamreisnz** [comment]
Hi, thanks for your feedback!

I normally don't tend to send messages back to the client, because usually I handle these things on the client. For example, if I try to login, and I get a 401 response, the client knows that login failed. Or when I send a password reset email and I get a 200 response, I know it was sent correctly, so the client is in charge of all the messages.

However, you are free to append any data with responses that you like. Simply change:

```js
res.end();
```

Into something like:

```js
res.json({message: 'Password reset token sent to your email'});
```

And handle it on the client accordingly.

Hope this helps.

**Comment by sadiqhabib** [comment]
Thank you for your quick response. 
I will also like to use your method because then its good and easy way to implement client side messages.
The reason y i asked this question because I wanted to know your opinion about these messages.

**Comment by adamreisnz** [comment]
Cheers, no worries
